
service: sales-service
app: thesis-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource:
            - arn:aws:sns:*:*:*
        - Effect: "Allow"
          Action:
            - "sqs:sendmessage"
          Resource:
            - arn:aws:sqs:*:*:*
  
  httpApi:
    cors: true
    authorizers:
      cognitoAuth:
        type: "jwt"
        identitySource: $request.header.Authorization
        issuerUrl: ${file(../config.json):CognitoIssuerUrl}
        audience:
          - ${file(../config.json):CognitoIdClient}

  environment:
    DBHost: ${file(../config.json):DBHost}
    DBPort: ${file(../config.json):DBPort}
    DBUser: ${file(../config.json):DBUser}
    DBPass: ${file(../config.json):DBPass}
    DBName: ${file(./config.json):DBName}
    FIREBASE_KEY: ${file(../config.json):FirebaseKey}
    LogMessageQueueUrl: ${file(../config.json):LogMessageQueueUrl}
    OnPostShipmentTopicArn: !GetAtt OnPostShipmentTopic.TopicArn

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  CustomerList:
    handler: bin/customer-list
    events:
    - httpApi:
        path: /customerlist/{param}
        method: GET
        authorizer:
          name: cognitoAuth
  CustomerCard:
    handler: bin/customer-card
    events:
    - httpApi:
        path: /customercard/{param}
        method: GET
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /customercard
        method: POST
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /customercard
        method: PATCH
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /customercard
        method: DELETE
        authorizer:
          name: cognitoAuth
  SalesOrderList:
    handler: bin/sales-order-list
    events:
    - httpApi:
        path: /salesorderlist/{param}
        method: GET
        authorizer:
          name: cognitoAuth
  SalesOrderCard:
    handler: bin/sales-order-card
    events:
    - httpApi:
        path: /salesordercard/{param}
        method: GET
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /salesordercard
        method: POST
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /salesordercard
        method: PATCH
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /salesordercard
        method: DELETE
        authorizer:
          name: cognitoAuth
  SalesOrderLineList:
    handler: bin/sales-order-line-list
    events:
    - httpApi:
        path: /salesorderlinelist/{param}
        method: GET
        authorizer:
          name: cognitoAuth
  SalesOrderLineCard:
    handler: bin/sales-order-line-card
    events:
    - httpApi:
        path: /salesorderlinecard/{param}
        method: GET
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /salesorderlinecard
        method: POST
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /salesorderlinecard
        method: PATCH
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /salesorderlinecard
        method: DELETE
        authorizer:
          name: cognitoAuth
  ChangeOrderStatus:
    handler: bin/change-order-status
    events:
      - sqs:
          arn: !GetAtt ChangeOrderStatusQueue.Arn
          batchSize: 1

resources:
  Resources:
    OnPostShipmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: OnPostShipment
    ChangeOrderStatusQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ChangeOrderStatus.fifo
        FifoQueue: true
        ContentBasedDeduplication: true

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
