
service: financial-service
app: thesis-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource:
            - arn:aws:sns:*:*:*
        - Effect: "Allow"
          Action:
            - "sqs:sendmessage"
          Resource:
            - arn:aws:sqs:*:*:*
  
  httpApi:
    cors: true
    authorizers:
      cognitoAuth:
        type: "jwt"
        identitySource: $request.header.Authorization
        issuerUrl: ${file(../config.json):CognitoIssuerUrl}
        audience:
          - ${file(../config.json):CognitoIdClient}

  environment:
    DBHost: ${file(../config.json):DBHost}
    DBPort: ${file(../config.json):DBPort}
    DBUser: ${file(../config.json):DBUser}
    DBPass: ${file(../config.json):DBPass}
    DBName: ${file(./config.json):DBName}
    ChangeOrderStatusQueueUrl: ${file(../config.json):ChangeOrderStatusQueueUrl}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  InvoiceList:
    handler: bin/invoice-list
    events:
    - httpApi:
        path: /invoicelist/{param}
        method: GET
        authorizer:
          name: cognitoAuth
  InvoiceCard:
    handler: bin/invoice-card
    events:
    - httpApi:
        path: /invoicecard/{param}
        method: GET
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /invoicecard
        method: POST
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /invoicecard
        method: PATCH
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /invoicecard
        method: DELETE
        authorizer:
          name: cognitoAuth
  InvoiceLineList:
    handler: bin/invoice-line-list
    events:
    - httpApi:
        path: /invoicelinelist/{param}
        method: GET
        authorizer:
          name: cognitoAuth
  InvoiceLineCard:
    handler: bin/invoice-line-card
    events:
    - httpApi:
        path: /invoicelinecard/{param}
        method: GET
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /invoicelinecard
        method: POST
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /invoicelinecard
        method: PATCH
        authorizer:
          name: cognitoAuth
    - httpApi:
        path: /invoicelinecard
        method: DELETE
        authorizer:
          name: cognitoAuth
  PostInvoice:
    handler: bin/post-invoice
    events:
      - sns:
          arn: ${file(../config.json):OnAfterPostingShptTopicArn}
