
service: utility-service
app: thesis-server

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource:
            - arn:aws:sns:*:*:*
        - Effect: "Allow"
          Action:
            - "sqs:sendmessage"
          Resource:
            - arn:aws:sqs:*:*:*
  
  httpApi:
    cors: true
    authorizers:
      cognitoAuth:
        type: "jwt"
        identitySource: $request.header.Authorization
        issuerUrl: ${file(../config.json):CognitoIssuerUrl}
        audience:
          - ${file(../config.json):CognitoIdClient}

  environment:
    RDSHost: ${file(../config.json):RDSHost}
    RDSPort: ${file(../config.json):RDSPort}
    RDSUser: ${file(../config.json):RDSUser}
    RDSPass: ${file(../config.json):RDSPass}
    RDSName: ${file(./config.json):RDSName}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  LogMessage:
    handler: bin/log-message
    events:
      - sqs:
          arn: !GetAtt LogMessageQueue.Arn
          batchSize: 1

resources:
  Resources:
    LogMessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: LogMessage.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
