
service: whse-service
app: thesis-server
org: thomas-cristofaro

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource:
            - arn:aws:sns:*:*:*
        - Effect: "Allow"
          Action:
            - "sqs:sendmessage"
          Resource:
            - arn:aws:sqs:*:*:*

  environment:
    OnAfterPostingShptTopicArn: !GetAtt OnAfterPostingShptTopic.TopicArn
    ChangeOrderStatus: URL

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  onafterpostingorder:
    handler: bin/onafterpostingorder
    events:
      - sqs: 
          arn: !GetAtt TestServerlessQueue.Arn
      # - sns:
      #     arn: !Ref TestServerlessTopic
      #     topicName: TestServerless

resources:
  Resources:
    OnAfterPostingShptTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: OnAfterPostingShpt

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
